<Project Sdk="Microsoft.NET.Sdk">

	<!-- Allgemeien Projekt-Einstellungen -->
	<Import Project="$(CommonProjectSettingsProps)" Condition="!$(CommonProjectSettingsPropsImported)"/>

	<PropertyGroup>
		<RootNamespace />
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Wellenlib\src\Wellenlib\Wellenlib.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
	</ItemGroup>

</Project>
