<Project Sdk="Microsoft.NET.Sdk">

	<!-- Allgemeien Projekt-Einstellungen -->
	<Import Project="$(CommonProjectSettingsProps)" Condition="!$(CommonProjectSettingsPropsImported)"/>
	
	<ItemGroup>
	  <ProjectReference Include="..\Gravity.SimulationEngine.Serialization\Gravity.SimulationEngine.Serialization.csproj" />
	  <ProjectReference Include="..\Gravity.SimulationEngine\Gravity.SimulationEngine.csproj" />
	</ItemGroup>

</Project>