<Project Sdk="Microsoft.NET.Sdk">

	<!-- Allgemeien Projekt-Einstellungen -->
	<Import Project="$(CommonProjectSettingsProps)" Condition="!$(CommonProjectSettingsPropsImported)"/>

	<ItemGroup>
	  <ProjectReference Include="..\..\Wellenlib\src\Wellenlib\Wellenlib.csproj" />
	</ItemGroup>

</Project>
